# Generated by Django 5.1.1 on 2024-09-25 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('message', models.TextField()),
            ],
        ),
    ]
