# Generated by Django 5.1.1 on 2024-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_status',
            field=models.BooleanField(default=True),
        ),
    ]
