# Generated by Django 5.1.1 on 2024-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeyGatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2)),
                ('token', models.CharField(max_length=15)),
            ],
        ),
    ]
