# Generated by Django 5.1.1 on 2024-10-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_zarinpalgatewaytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarinpalgatewaytransaction',
            name='ref_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
