# Generated by Django 5.1.1 on 2024-10-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_zarinpalgatewaytransaction_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zarinpalgatewaytransaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
