# Generated by Django 5.1.1 on 2024-09-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='plant-images/')),
                ('description', models.TextField()),
                ('plant_code', models.CharField(max_length=5)),
                ('inventory', models.IntegerField()),
                ('tax', models.IntegerField()),
            ],
        ),
    ]
