# Generated by Django 5.1.1 on 2024-09-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='plant_code',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tax',
            new_name='unit_tax',
        ),
    ]
