# Generated by Django 5.1.1 on 2024-09-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_plant_code_product_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_tax',
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
